name: Deploy Java project to Azure Function App

on:
  push:
    branches: [ "master" ]

env:
  POM_XML_DIRECTORY: '.'
  JAVA_VERSION: '17'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: Setup Java Sdk ${{ env.JAVA_VERSION }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: 'Build artifact'
        shell: bash
        run: |
          pushd './${{ env.POM_XML_DIRECTORY }}'
          chmod a+x gradlew
          ./gradlew build azureFunctionsPackage
          popd

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: build/azure-functions/default
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
